### ISSUE TITLE
RF 2.8.7 support

### ISSUE THREAD

**Issue by uSpike** [userzimmermann/robotframework-python3#1]
Hi,

I was wondering if there's any plans to support RF 2.8.7 with this Python3 fork?  I am not very informed about what goes in to the compatibility layer, but I would be happy to help if possible/needed.

I currently need the fix in https://github.com/robotframework/robotframework/issues/1848 for my application.

Thanks!

**Comment by userzimmermann** [comment]
Hi.
My plan is to continue and stay up to date with every new release. But time doesn't like my plan so much ;) I already thought some days ago that I should do some update to the latest version soon. I will try to achieve that next week.

Merging is usually not that big deal. The hardest part is always to make new acceptance tests
python3 compatible. And to find all these little new code pieces or changes
which don't break the basic robotframework functionality in python3 but which lead to (sometimes strange) incompatibility effects in certain cases and make a lot of unit and acceptance tests fail.

You could of course help with checking tests and finding/fixing failure causes. Thanks for your offer :) After basic merging with latest release I could open an issue for every failing test. So you could just pick some of them...

The only real "compatibility layer" is six. The rest are mostly changes of old-style python<=2.5 syntax and workarounds for bytes/str/unicode/buffer/conversion/encoding-related inconsistencies between python 2/3.

**Comment by userzimmermann** [comment]
Hi.
This repository is now obsolete.
All further development takes place in the **python3** branch of:

https://github.com/userzimmermann/robotframework

I merged with **robotframework-2.8.6** and made a new release.
I also created issues for failing acceptance tests.
I will continue with **2.8.7** and then getting regularly in sync with new commits.

**Comment by userzimmermann** [comment]
You can get additional info about the current progress at:

https://github.com/robotframework/robotframework/pull/1811
https://github.com/robotframework/robotframework/issues/1928

**Comment by userzimmermann** [comment]
2.8.7 release is done:

https://pypi.python.org/pypi/robotframework-python3/2.8.7
https://github.com/userzimmermann/robotframework/releases/tag/python3-2.8.7
